# Site settings
title: JGiven
description: "A developer-friendly BDD tool for Java"
baseurl: ""
url: "http://jgiven.org"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

kramdown:
    input: GFM

version: 0.17.1

