[versions]
aspectj-version = "1.9.24"
byteBuddy-version = "1.17.7"
gsonVersion = "2.13.1"
guavaVersion = "33.4.8-jre"
jakarta-version = "3.0.0"
junit4-version = "4.13.2"
paranamerVersion = "2.8.3"
slf4j-version = "2.0.17"
spring-version = "6.2.10"
androidx-test-version = "1.7.0"

[libraries]
androidGradlePlugin = { module = "com.android.tools.build:gradle", version = "8.12.1"}
androidx-appcompat = {module = "androidx.appcompat:appcompat", version = "1.7.1"}
androidx-test-core = {module = "androidx.test:core", version.ref = "androidx-test-version"}
androidx-test-rules = {module = "androidx.test:rules", version.ref = "androidx-test-version"}
androidx-test-junit = {module = "androidx.test.ext:junit", version = "1.3.0"}
assertj = { module = "org.assertj:assertj-core", version = "3.27.4" }
aspectj-jrt = { module = "org.aspectj:aspectjrt", version.ref = "aspectj-version" }
aspectj-jweaver = { module = "org.aspectj:aspectjweaver", version.ref = "aspectj-version" }
byteBuddy = { module = "net.bytebuddy:byte-buddy", version.ref = "byteBuddy-version" }
byteBuddy-agent = { module = "net.bytebuddy:byte-buddy-agent", version.ref = "byteBuddy-version" }
gson = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
guava = { module = "com.google.guava:guava", version.ref = "guavaVersion" }
hypersql-database = { module = "org.hsqldb:hsqldb", version = "2.7.4" }
jakarta-annotation = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-version" }
junit-bom = { module = "org.junit:junit-bom", version = "5.13.4" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit4 = { module = "junit:junit", version.ref = "junit4-version" }
junit4-dataprovider = { module = "com.tngtech.java:junit-dataprovider", version = "1.13.1" }
junit4-params = { module = "pl.pragmatists:JUnitParams", version = "1.1.1" }
paranamer = { module = "com.thoughtworks.paranamer:paranamer", version.ref = "paranamerVersion" }
quickcheck = { module = "net.java.quickcheck:quickcheck", version = "0.6" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-version" }
slf4j-java-util-logging = { module = "org.slf4j:slf4j-jdk14", version.ref = "slf4j-version" }
spring-context = { module = "org.springframework:spring-context", version.ref = "spring-version" }
spring-test = { module = "org.springframework:spring-test", version.ref = "spring-version" }
spring-tx = { module = "org.springframework:spring-tx", version.ref = "spring-version" }
spring-jdbc = { module = "org.springframework:spring-jdbc", version.ref = "spring-version" }
testng = { module = "org.testng:testng", version="7.11.0" }

[bundles]
junit4 = [ "junit4", "junit4-dataprovider", "junit4-params" ]
spring-test = [ "spring-context", "spring-test", "spring-tx", "spring-jdbc" ]
spring-compile = [ "spring-context", "spring-test" ]
aspectj-spring-test = [ "aspectj-jrt", "aspectj-jweaver" ]

[plugins]
byteBuddy-plugin = { id = "net.bytebuddy:byte-buddy-gradle-plugin", version.ref = "byteBuddy-version" }
