name: Align gh-pages branch
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Rebase gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
        with:
          fetch-depth: '0' #fetch all history
          ref: 'gh-pages'
      - name: Configure git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Rebase on master
        run:  git rebase origin/master
      - name: Replace version on origin
        run: git push --force-with-lease
